version: "3.3"
services:
  frontend:
    image: sohailshaikh23/3-tier_frontend:latest
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_BACKEND_URL: "http://15.207.108.244:8080/api/tasks"
    networks:
      - notes-webapp

  api:
    image: sohailshaikh23/3-tier_backend:latest
    container_name: api
    ports:
      - "8080:8080"
    environment:
      MONGO_CONN_STR: "mongodb://mongo:27017/todo"
      MONGO_USERNAME: "admin"
      MONGO_PASSWORD: "admin"
    networks:
      - notes-webapp
    depends_on:
      - db

  db:
    image: sohailshaikh23/3-tier_mongo:4.4.6
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_USERNAME: "admin"
      MONGO_PASSWORD: "admin"
    networks:
      - notes-webapp

networks:
  notes-webapp:
