apiVersion: apps/v1
kind: Deployment
metadata: 
  name: api
  namespace: notes-webapp
  labels: 
    role: api
    env: demo
    app: api
spec: 
  replicas: 3
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector: 
    matchLabels:
      role: api
      app: api
  template:
    metadata:
      labels:
        role: api
        app: api
    spec:
     containers:
      - name: api
        image: sohailshaikh23/3-tier_backend:latest
        imagePullPolicy: Always
        env:
          - name: MONGO_CONN_STR
            value: mongo://mongo-0.mongo,mongo-1.mongo,mongo-2.mongo:27017/todo?replicaSet=rs0
          - name: MONGO_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: username
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: password
        ports:
        - containerPort: 8080
        livenessProbe: 
          httpGet:
            path: /ok
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ok
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
