apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: notes-webapp
spec: 
  ports:
   - protocol: TCP
     port: 80
     targetPort: 8080
     name: http
  type: ClusterIP
  selector:
    role: api
    app: api
