apiVersion: v1
kind: Service
metadata: 
  name: frontend
  namespace: notes-webapp
spec:
  ports:
   - port: 80   # service port 
     targetPort: 3000   # container port
     protocol: TCP
  type: ClusterIP
  selector:
    role: frontend
    app: frontend
