apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: notes-webapp
  name: mongodb
spec:
  serviceName: mongo
  replicas: 3
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
        replicaset: rs0.main
    spec:
      containers:
      - name: mongo
        image: <your_mongo_image>
        command:
          - "numactl"
          - "--interleave=all"
          - "mongod"
          - "--wiredTigerCacheSizeGB"
          - "0.1"
          - "--bind_ip"
          - "0.0.0.0"
          - "replSet"
          - "rs0"
        ports:
          - containerPort: 27017
        volumeMounts:
          - name: mongodb-persistent-storage-claim
            mountPath: /data/db
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: password
  volumeClaimTemplates:
  - metadata:
      name: mongodb-persistent-storage-claim
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: gp2
      resources:
        requests:
          storage: 1Gi

