apiVersion: v1
kind: Service
metadata:
  namespace: notes-webapp
  name: mongo
  labels:
    app: db
spec:
  clusterIP: None
  selector:
    app: db
  ports:
    - port: 27017
      targetPort: 27017
      
